services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    restart: always

  frontend: 
    build:
      context: ./frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    restart: always

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: cities_password
      POSTGRES_DB: cities_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgres/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"

volumes:
  pg_data: